from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, JSON, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from .database import Base


class User(Base):
    """User model with Clerk integration and profile information"""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    clerk_user_id = Column(String, unique=True, nullable=False, index=True)
    email = Column(String, unique=True, index=True)
    username = Column(String, unique=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # User's books and offers
    books = relationship("Book", back_populates="owner")
    sent_offers = relationship(
        "SwapOffer",
        back_populates="sender",
        foreign_keys="SwapOffer.sender_id"
    )
    received_offers = relationship(
        "SwapOffer",
        back_populates="receiver",
        foreign_keys="SwapOffer.receiver_id"
    )


class Book(Base):
    """Book model with LLM-enhanced fields for semantic matching"""
    __tablename__ = "books"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    author = Column(String, nullable=False)
    description = Column(Text)
    condition = Column(String)
    owner_id = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # LLM-enhanced fields
    llm_summary = Column(Text)  # Cached LLM-generated summary
    semantic_tags = Column(JSON)  # List of semantic tags generated by LLM
    match_vector = Column(JSON)  # Vector representation for semantic matching

    # Relationships
    owner = relationship("User", back_populates="books")
    offers_as_requested = relationship(
        "SwapOffer",
        back_populates="requested_book",
        foreign_keys="SwapOffer.requested_book_id"
    )
    offers_as_offered = relationship(
        "SwapOffer",
        back_populates="offered_book",
        foreign_keys="SwapOffer.offered_book_id"
    )


class SwapOffer(Base):
    """SwapOffer model for book exchange requests"""
    __tablename__ = "swap_offers"

    id = Column(Integer, primary_key=True, index=True)
    sender_id = Column(Integer, ForeignKey("users.id"))
    receiver_id = Column(Integer, ForeignKey("users.id"))
    offered_book_id = Column(Integer, ForeignKey("books.id"))
    requested_book_id = Column(Integer, ForeignKey("books.id"))
    status = Column(String)  # pending, accepted, rejected, completed
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    sender = relationship(
        "User",
        back_populates="sent_offers",
        foreign_keys=[sender_id]
    )
    receiver = relationship(
        "User",
        back_populates="received_offers",
        foreign_keys=[receiver_id]
    )
    offered_book = relationship(
        "Book",
        back_populates="offers_as_offered",
        foreign_keys=[offered_book_id]
    )
    requested_book = relationship(
        "Book",
        back_populates="offers_as_requested",
        foreign_keys=[requested_book_id]
    )
